#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace
{
	std::vector<unsigned char> readFile(const std::filesystem::path &path)
	{
		std::ifstream input(path, std::ios::binary | std::ios::ate);
		if (!input)
		{
			throw std::runtime_error("Could not open resource: " + path.string());
		}

		const auto size = input.tellg();
		if (size < 0)
		{
			throw std::runtime_error("Could not determine resource size: " + path.string());
		}

		std::vector<unsigned char> result(static_cast<std::size_t>(size));
		input.seekg(0);
		if (!result.empty() && !input.read(reinterpret_cast<char *>(result.data()), size))
		{
			throw std::runtime_error("Could not read resource: " + path.string());
		}
		return result;
	}

	std::string escapeString(std::string_view value)
	{
		std::string result;
		for (const char character : value)
		{
			switch (character)
			{
			case '\\':
				result += "\\\\";
				break;
			case '"':
				result += "\\\"";
				break;
			default:
				result += character;
				break;
			}
		}
		return result;
	}

	std::string readTextFile(const std::filesystem::path &path)
	{
		std::ifstream input(path, std::ios::binary);
		return {std::istreambuf_iterator<char>(input), std::istreambuf_iterator<char>()};
	}

	void writeIfDifferent(const std::filesystem::path &path, const std::string &content)
	{
		if (std::filesystem::exists(path) && readTextFile(path) == content)
		{
			return;
		}

		std::filesystem::create_directories(path.parent_path());
		std::ofstream output(path, std::ios::binary | std::ios::trunc);
		if (!output || !output.write(content.data(), static_cast<std::streamsize>(content.size())))
		{
			throw std::runtime_error("Could not write generated source: " + path.string());
		}
	}
}

int main(int argc, char **argv)
{
	if (argc < 3)
	{
		std::cerr << "Usage: sparkleResourceBuilder <root> <output.cpp> [relative-resource ...]\n";
		return 1;
	}

	try
	{
		const std::filesystem::path root = argv[1];
		const std::filesystem::path outputPath = argv[2];
		std::ostringstream output;
		output << "// Generated by sparkleResourceBuilder. Do not edit.\n"
			   << "#include \"resource.hpp\"\n\n"
			   << "#include <algorithm>\n"
			   << "#include <array>\n"
			   << "#include <stdexcept>\n"
			   << "#include <string>\n\n"
			   << "namespace\n{\n";

		for (int index = 3; index < argc; ++index)
		{
			const auto data = readFile(root / std::filesystem::path(argv[index]));
			output << "\tconstexpr std::array<std::byte, " << data.size() << "> resource" << (index - 3) << " = {";
			for (std::size_t byteIndex = 0; byteIndex < data.size(); ++byteIndex)
			{
				if (byteIndex % 16 == 0)
				{
					output << "\n\t\t";
				}
				output << "std::byte{0x" << std::hex << std::setw(2) << std::setfill('0') << static_cast<unsigned int>(data[byteIndex]) << "}, ";
			}
			output << std::dec << "\n\t};\n\n";
		}

		output << "\tstruct Entry\n\t{\n\t\tstd::string_view path;\n\t\tspk::resources::Data data;\n\t};\n\n"
			   << "\tconstexpr std::array<Entry, " << (argc - 3) << "> entries = {{\n";
		for (int index = 3; index < argc; ++index)
		{
			const auto key = std::filesystem::path(argv[index]).generic_string();
			output << "\t\t{\"" << escapeString(key) << "\", resource" << (index - 3) << "},\n";
		}
		output << "\t}};\n}\n\n"
			   << "namespace spk::resources\n{\n"
			   << "\tstd::optional<Data> find(std::string_view path) noexcept\n\t{\n"
			   << "\t\tconst auto it = std::lower_bound(entries.begin(), entries.end(), path, [](const Entry &entry, std::string_view value) { return entry.path < value; });\n"
			   << "\t\tif (it == entries.end() || it->path != path)\n\t\t{\n\t\t\treturn std::nullopt;\n\t\t}\n\t\treturn it->data;\n\t}\n\n"
			   << "\tData get(std::string_view path)\n\t{\n\t\tconst auto result = find(path);\n\t\tif (!result)\n\t\t{\n\t\t\tthrow std::out_of_range(\"Unknown embedded resource: \" + std::string(path));\n\t\t}\n\t\treturn *result;\n\t}\n\n"
			   << "\tbool contains(std::string_view path) noexcept\n\t{\n\t\treturn find(path).has_value();\n\t}\n\n"
			   << "\tstd::string_view text(std::string_view path)\n\t{\n\t\tconst auto data = get(path);\n\t\treturn {reinterpret_cast<const char *>(data.data()), data.size()};\n\t}\n}\n";

		writeIfDifferent(outputPath, output.str());
		return 0;
	}
	catch (const std::exception &exception)
	{
		std::cerr << "sparkleResourceBuilder: " << exception.what() << '\n';
		return 1;
	}
}
