#pragma once

#include <random>
#include "miscellaneous/JSON/spk_JSON_object.hpp"

namespace spk
{
	/**
	 * @class RandomGenerator
	 * 
	 * @tparam TGeneratedType The type of value to generate. Must be a arithmetic type (e.g., int, float, double).
	 * 
	 * @brief Template class for generating random values of a specified numeric type within a given range.
	 *
	 * This class offers a versatile random number generation capability for various numeric types,
	 * supporting both integral and floating-point values. It utilizes the C++ `<random>` library to
	 * ensure high-quality and statistically uniform random values. Users can customize the seed and range
	 * to control the behavior of the generator.
	 *
	 * The generator employs different distribution types based on the numeric type chosen.
	 * For integral types, it uses `std::uniform_int_distribution`, while for floating-point types, it
	 * uses `std::uniform_real_distribution`. This design ensures that random values are generated appropriately
	 * for each type.
	 *
	 * Usage example:
	 * @code
	 * spk::RandomGenerator<float> rng;
	 * rng.configureSeed(42);
	 * rng.configureRange(0.0f, 1.0f);
	 * float randomValue = rng.sample(); // Generate a random float between 0.0 and 1.0
	 * @endcode
	 *
	 * @note The configuration options, such as seed and range, provide control over the randomness of generated values, making this class suitable for various applications requiring random data.
	 */

	template < typename TGeneratedType = int >
	class RandomGenerator
	{
	private:
		using GeneratorType = typename std::conditional<
			std::is_same<TGeneratedType, double>::value || std::is_same<TGeneratedType, float>::value,
			std::uniform_real_distribution<TGeneratedType>,
			std::uniform_int_distribution<TGeneratedType>
		>::type;

		std::mt19937 _generator;
		GeneratorType _distribution;

	public:
		/**
		 * @brief Default constructor initializing the random generator with a random seed.
		 * 
		 * Initializes the random number generator using a seed obtained from `std::random_device`. This ensures a unique sequence of random values for each instance of `RandomGenerator`.
		 */
		RandomGenerator() :
			_generator(std::random_device()()),
			_distribution()
		{}

		/**
		 * @brief Constructor that initializes the random generator with a specified seed.
		 * 
		 * Allows for deterministic random number generation by providing a specific seed value. Useful for reproducibility in tests or simulations.
		 * 
		 * @param p_seed The seed value used to initialize the random number generator.
		 */
		RandomGenerator(const unsigned int& p_seed) :
			_generator(p_seed),
			_distribution()
		{}

		/**
		 * @brief Deletes the copy constructor to prevent copying instances.
		 * 
		 * Ensures that `RandomGenerator` objects cannot be copied, which is important to maintain the uniqueness of each generator's random number sequence.
		 */
		RandomGenerator(const RandomGenerator& p_other) = delete;

		/**
		 * @brief Configures the seed of the random number generator.
		 * 
		 * Sets a new seed value for the random number generator, allowing the sequence of generated numbers to be reset or made reproducible.
		 * 
		 * @param p_seed The new seed value for the generator.
		 */
		void configureSeed(const uint64_t& p_seed)
		{
			_generator = std::mt19937(p_seed);
		}

		/**
		 * @brief Configures the range of values the generator produces.
		 * 
		 * Sets the minimum and maximum values for the generated numbers, defining the range of possible outcomes.
		 * 
		 * @param p_min The minimum value that can be generated.
		 * @param p_max The maximum value that can be generated.
		 */
		void configureRange(const TGeneratedType& p_min, const TGeneratedType& p_max)
		{
			_distribution.param(typename GeneratorType::param_type(p_min, p_max));
		}

		/**
		 * @brief Samples a random value within the configured range.
		 * 
		 * Generates a random value of `TGeneratedType` within the range specified by `configureRange`. The distribution of values depends on whether `TGeneratedType` is an integral or floating-point type.
		 * 
		 * @return A randomly generated value within the specified range.
		 */
		constexpr TGeneratedType sample() { return _distribution(_generator); }

		/**
		 * @brief Gets the minimum value that can be generated by the current configuration.
		 * 
		 * @return The minimum value of the distribution range.
		 */
		constexpr TGeneratedType min() const { return _distribution.min(); }

		/**
		 * @brief Gets the maximum value that can be generated by the current configuration.
		 * 
		 * @return The maximum value of the distribution range.
		 */
		constexpr TGeneratedType max() const { return _distribution.max(); }
	};
}
